# Generated by Django 3.1 on 2020-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_movie_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_start',
        ),
        migrations.AddField(
            model_name='ticket',
            name='nos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
